language: node_js
node_js:
  - '0.10'
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - gem install sass
  - gem install compass
  - 'npm install -g bower grunt-cli karma'
  - 'bower install'
